name: JustForFun
main: org.justforfun.Main
version: 2.0-BISMILLAH-SIGMA
api-version: 1.20
commands:
  justforfun:
    description: Main command for JustForFun plugin
    usage: /<command> <subcommand>
    aliases: [jff]
    permission: justforfun.use
    permission-message: You do not have permission to use this command.
permissions:
  justforfun.use:
    description: Allows usage of JustForFun commands
    default: op
  justforfun.reload:
    description: Allows reloading the plugin configuration
    default: op
  justforfun.rename:
    description: Allows renaming of scoreboard IDs
    default: op
  justforfun.delete:
    description: Allows deletion of scoreboard IDs
    default: op
